[book]
title = "COMP 4630 | Winter 2026"
authors = ["Charlotte Curtis"]
description = "Machine Learning for CS at MRU"
src = "."


[output.html]
sidebar-header-nav = true
no-section-label = true 

# Use katex for math instead of broken mathjax
# [preprocessor.katex]
# after = ["links"]

# strip yaml front matter (from marp md)
[preprocessor.marp]
command = "cargo run --manifest-path=crates/mdbook-marp/Cargo.toml --locked"