[book]
title = "COMP 4630 | Winter 2026"
authors = ["Charlotte Curtis"]
description = "Machine Learning for CS at MRU"
src = "."

[output.html]
sidebar-header-nav = true
no-section-label = true
git-repository-url = "https://github.com/mru-comp4630/w26"
site-url = "/w26/"

[output.html.fold]
enable = true
level = 0

# Use katex for math instead of broken mathjax
[preprocessor.katex]
after = ["links"]
command = "cargo run --manifest-path=crates/mdbook-katex/Cargo.toml --locked"

# strip yaml front matter (from marp md)
[preprocessor.marp]
command = "cargo run --manifest-path=crates/mdbook-marp/Cargo.toml --locked"
semester = "/w26"