[package]
name = "mdbook-marp"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
mdbook-preprocessor = "0.5.1"
pulldown-cmark = "0.13.0"
pulldown-cmark-to-cmark = "21.1.0"
serde_json = "1.0.145"
regex = "1.12.2"
mdbook-driver = "0.5.1"

[[bin]]
name = "mdbook-marp"
